spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
  messages:
    basename: messages, errors

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace